"""add items table and species evolution columns

Revision ID: 138fa0de794a
Revises: fdd89ef112d7
Create Date: 2026-07-07 19:06:53.674858

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "138fa0de794a"
down_revision: Union[str, Sequence[str], None] = "fdd89ef112d7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "items",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("category", sa.String(), nullable=False),
        sa.Column("fling_power", sa.Integer(), nullable=True),
        sa.Column("sprite_url", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("species", sa.Column("prevo", sa.String(), nullable=True))
    # server_default backfills existing rows (seeded before this migration) with an
    # empty array; the ORM-level default=list only applies to new inserts.
    op.add_column(
        "species",
        sa.Column("evos", sa.ARRAY(sa.String()), nullable=False, server_default="{}"),
    )
    op.add_column("species", sa.Column("evo_type", sa.String(), nullable=True))
    op.add_column("species", sa.Column("evo_level", sa.Integer(), nullable=True))
    op.add_column("species", sa.Column("evo_item", sa.String(), nullable=True))
    op.add_column("species", sa.Column("evo_move", sa.String(), nullable=True))
    op.add_column("species", sa.Column("evo_condition", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("species", "evo_condition")
    op.drop_column("species", "evo_move")
    op.drop_column("species", "evo_item")
    op.drop_column("species", "evo_level")
    op.drop_column("species", "evo_type")
    op.drop_column("species", "evos")
    op.drop_column("species", "prevo")
    op.drop_table("items")
    # ### end Alembic commands ###
