"""add species description column

Revision ID: 19edf678d078
Revises: 49d819dd1ae1
Create Date: 2026-07-16 13:35:51.269126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19edf678d078'
down_revision: Union[str, Sequence[str], None] = '49d819dd1ae1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('species', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('species', 'description')
    # ### end Alembic commands ###
