"""add usage_stats table

Revision ID: 49d819dd1ae1
Revises: cacc130ca313
Create Date: 2026-07-08 10:03:44.899599

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "49d819dd1ae1"
down_revision: Union[str, Sequence[str], None] = "cacc130ca313"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "usage_stats",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("format", sa.String(), nullable=False),
        sa.Column("month", sa.String(), nullable=False),
        sa.Column("species_id", sa.String(), nullable=False),
        sa.Column("species_name", sa.String(), nullable=False),
        sa.Column("rank", sa.Integer(), nullable=False),
        sa.Column("usage_percent", sa.Float(), nullable=False),
        sa.Column("raw_count", sa.Integer(), nullable=False),
        sa.Column("abilities", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("items", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("moves", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("tera_types", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("teammates", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("checks_and_counters", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "synced_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("format", "species_id", name="uq_usage_stats_format_species"),
    )
    op.create_index(op.f("ix_usage_stats_format"), "usage_stats", ["format"], unique=False)
    op.create_index(op.f("ix_usage_stats_species_id"), "usage_stats", ["species_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_usage_stats_species_id"), table_name="usage_stats")
    op.drop_index(op.f("ix_usage_stats_format"), table_name="usage_stats")
    op.drop_table("usage_stats")
    # ### end Alembic commands ###
