"""add gin index on species learnable_moves

Revision ID: 5284c19a5987
Revises: 138fa0de794a
Create Date: 2026-07-07 19:12:51.587256

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "5284c19a5987"
down_revision: Union[str, Sequence[str], None] = "138fa0de794a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_species_learnable_moves_gin",
        "species",
        ["learnable_moves"],
        unique=False,
        postgresql_using="gin",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_species_learnable_moves_gin", table_name="species", postgresql_using="gin")
    # ### end Alembic commands ###
