"""add pokedex reference tables

Revision ID: e619ce2f2db8
Revises:
Create Date: 2026-07-07 16:27:46.276760

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e619ce2f2db8"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "abilities",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "moves",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("category", sa.String(), nullable=False),
        sa.Column("base_power", sa.Integer(), nullable=True),
        sa.Column("accuracy", sa.Integer(), nullable=True),
        sa.Column("pp", sa.Integer(), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("target", sa.String(), nullable=False),
        sa.Column("flags", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_moves_type"), "moves", ["type"], unique=False)
    op.create_table(
        "natures",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("increased_stat", sa.String(), nullable=True),
        sa.Column("decreased_stat", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "species",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("num", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("base_species", sa.String(), nullable=True),
        sa.Column("forme", sa.String(), nullable=True),
        sa.Column("type1", sa.String(), nullable=False),
        sa.Column("type2", sa.String(), nullable=True),
        sa.Column("base_stats", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("abilities", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("learnable_moves", sa.ARRAY(sa.String()), nullable=False),
        sa.Column("sprite_url", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_species_base_species"), "species", ["base_species"], unique=False)
    op.create_index(op.f("ix_species_num"), "species", ["num"], unique=False)
    op.create_index(op.f("ix_species_type1"), "species", ["type1"], unique=False)
    op.create_index(op.f("ix_species_type2"), "species", ["type2"], unique=False)
    op.create_table(
        "type_matchups",
        sa.Column("attacking_type", sa.String(), nullable=False),
        sa.Column("defending_type", sa.String(), nullable=False),
        sa.Column("multiplier", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("attacking_type", "defending_type"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("type_matchups")
    op.drop_index(op.f("ix_species_type2"), table_name="species")
    op.drop_index(op.f("ix_species_type1"), table_name="species")
    op.drop_index(op.f("ix_species_num"), table_name="species")
    op.drop_index(op.f("ix_species_base_species"), table_name="species")
    op.drop_table("species")
    op.drop_table("natures")
    op.drop_index(op.f("ix_moves_type"), table_name="moves")
    op.drop_table("moves")
    op.drop_table("abilities")
    # ### end Alembic commands ###
