"""add move description column

Revision ID: fdd89ef112d7
Revises: e619ce2f2db8
Create Date: 2026-07-07 18:37:41.964523

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fdd89ef112d7"
down_revision: Union[str, Sequence[str], None] = "e619ce2f2db8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("moves", sa.Column("description", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("moves", "description")
    # ### end Alembic commands ###
